version: '3.8'

services:
  gwi_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    env_file:
      - .env.docker