version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    # volumes: 
    #  - ./.database:/var/lib/mysql
    ports:
      - 3306:3306

  # for viewing the database at http://localhost:8080
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080