// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/core/user/v1/user.proto

package user_pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UserInstance with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserInstance) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserInstance with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserInstanceMultiError, or
// nil if none found.
func (m *UserInstance) ValidateAll() error {
	return m.validate(true)
}

func (m *UserInstance) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserInstanceValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserInstanceValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserInstanceValidationError{
				field:  "Id",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.Username != nil {

		if m.GetUsername() != "" {

			if l := utf8.RuneCountInString(m.GetUsername()); l < 1 || l > 256 {
				err := UserInstanceValidationError{
					field:  "Username",
					reason: "value length must be between 1 and 256 runes, inclusive",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if len(errors) > 0 {
		return UserInstanceMultiError(errors)
	}

	return nil
}

// UserInstanceMultiError is an error wrapping multiple validation errors
// returned by UserInstance.ValidateAll() if the designated constraints aren't met.
type UserInstanceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserInstanceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserInstanceMultiError) AllErrors() []error { return m }

// UserInstanceValidationError is the validation error returned by
// UserInstance.Validate if the designated constraints aren't met.
type UserInstanceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserInstanceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserInstanceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserInstanceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserInstanceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserInstanceValidationError) ErrorName() string { return "UserInstanceValidationError" }

// Error satisfies the builtin error interface
func (e UserInstanceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserInstance.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserInstanceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserInstanceValidationError{}
