// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/helpers/AssetTypeValidator.go

// Package mock_helpers is a generated GoMock package.
package mock_helpers

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAssetTypeValidatorInterface is a mock of AssetTypeValidatorInterface interface.
type MockAssetTypeValidatorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAssetTypeValidatorInterfaceMockRecorder
}

// MockAssetTypeValidatorInterfaceMockRecorder is the mock recorder for MockAssetTypeValidatorInterface.
type MockAssetTypeValidatorInterfaceMockRecorder struct {
	mock *MockAssetTypeValidatorInterface
}

// NewMockAssetTypeValidatorInterface creates a new mock instance.
func NewMockAssetTypeValidatorInterface(ctrl *gomock.Controller) *MockAssetTypeValidatorInterface {
	mock := &MockAssetTypeValidatorInterface{ctrl: ctrl}
	mock.recorder = &MockAssetTypeValidatorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssetTypeValidatorInterface) EXPECT() *MockAssetTypeValidatorInterfaceMockRecorder {
	return m.recorder
}

// ValidateAssetType mocks base method.
func (m *MockAssetTypeValidatorInterface) ValidateAssetType(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAssetType", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateAssetType indicates an expected call of ValidateAssetType.
func (mr *MockAssetTypeValidatorInterfaceMockRecorder) ValidateAssetType(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAssetType", reflect.TypeOf((*MockAssetTypeValidatorInterface)(nil).ValidateAssetType), arg0)
}
