// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/core/opinion/v1/opinion.proto

package opinionpb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on OpinionCore with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OpinionCore) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OpinionCore with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OpinionCoreMultiError, or
// nil if none found.
func (m *OpinionCore) ValidateAll() error {
	return m.validate(true)
}

func (m *OpinionCore) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetQid()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OpinionCoreValidationError{
					field:  "Qid",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OpinionCoreValidationError{
					field:  "Qid",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetQid()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OpinionCoreValidationError{
				field:  "Qid",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetQidFromUser() == nil {
		err := OpinionCoreValidationError{
			field:  "QidFromUser",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetQidFromUser()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OpinionCoreValidationError{
					field:  "QidFromUser",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OpinionCoreValidationError{
					field:  "QidFromUser",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetQidFromUser()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OpinionCoreValidationError{
				field:  "QidFromUser",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetQidToAsset() == nil {
		err := OpinionCoreValidationError{
			field:  "QidToAsset",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetQidToAsset()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OpinionCoreValidationError{
					field:  "QidToAsset",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OpinionCoreValidationError{
					field:  "QidToAsset",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetQidToAsset()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OpinionCoreValidationError{
				field:  "QidToAsset",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.Md != nil {

		if all {
			switch v := interface{}(m.GetMd()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, OpinionCoreValidationError{
						field:  "Md",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, OpinionCoreValidationError{
						field:  "Md",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMd()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return OpinionCoreValidationError{
					field:  "Md",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Mmd != nil {

		if all {
			switch v := interface{}(m.GetMmd()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, OpinionCoreValidationError{
						field:  "Mmd",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, OpinionCoreValidationError{
						field:  "Mmd",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMmd()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return OpinionCoreValidationError{
					field:  "Mmd",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.IsFavourite != nil {
		// no validation rules for IsFavourite
	}

	if m.Stars != nil {

		if m.GetStars() != 0 {

			if val := m.GetStars(); val < 0 || val > 10 {
				err := OpinionCoreValidationError{
					field:  "Stars",
					reason: "value must be inside range [0, 10]",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if m.Asset != nil {

		if all {
			switch v := interface{}(m.GetAsset()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, OpinionCoreValidationError{
						field:  "Asset",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, OpinionCoreValidationError{
						field:  "Asset",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetAsset()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return OpinionCoreValidationError{
					field:  "Asset",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return OpinionCoreMultiError(errors)
	}

	return nil
}

// OpinionCoreMultiError is an error wrapping multiple validation errors
// returned by OpinionCore.ValidateAll() if the designated constraints aren't met.
type OpinionCoreMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OpinionCoreMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OpinionCoreMultiError) AllErrors() []error { return m }

// OpinionCoreValidationError is the validation error returned by
// OpinionCore.Validate if the designated constraints aren't met.
type OpinionCoreValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OpinionCoreValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OpinionCoreValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OpinionCoreValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OpinionCoreValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OpinionCoreValidationError) ErrorName() string { return "OpinionCoreValidationError" }

// Error satisfies the builtin error interface
func (e OpinionCoreValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOpinionCore.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OpinionCoreValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OpinionCoreValidationError{}
